# Generated by Django 3.1.5 on 2021-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210115_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='rszdimg',
            field=models.ImageField(null=True, upload_to='resized_pictures'),
        ),
    ]
